
trigger: none

pool:
  vmImage: 'windows-2025'

variables:
  group: akamai
  AKAMAI_ACCESS_TOKEN: $(accessToken)

steps:
  - task: PowerShell@2
    displayName: 'Run Maintenance Script with PowerShell'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Test 1 = $Test1"
        gci env:
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module Akamai.Netstorage -Force -Scope CurrentUser
        $Creds = Get-AkamaiCredentials
        Write-Host $Creds.Host
        $UploadAccount = Get-NetstorageUploadAccount -UploadAccountID akamaipowershell -Debug
      pwsh: true
