
trigger: none

schedules:
  - cron: "0 13 1 */3 *"  # Runs at 13:00 UTC (6:00 AM PST) on the 1st day every 3rd month
    displayName: "Quarterly Maintenance Run"
    branches:
      include:
        - main
    always: true

parameters:
  - name: Environment
    type: string
    default: Production
    values:
      - Production
      - Staging
      - RC
      - PPE

pool:
  vmImage: 'windows-latest'

variables:
  group: akamai-creds

steps:
  - task: AzurePowerShell@5
    displayName: 'Run Maintenance Script with Azure PowerShell'
    env:
      AKAMAI_HOST: $(AkamaiHost)
      AKAMAI_CLIENT_TOKEN: $(AkamaiClientToken)
      AKAMAI_ACCESS_TOKEN: $(AkamaiAccessToken)
      AKAMAI_CLIENT_SECRET: $(AkamaiClientSecret)
    inputs:
      # link to set up a service connection: https://aka.ms/azure-pipelines-service-connection
      azureSubscription: '<Your Azure Service Connection Name>'
      ScriptType: 'InlineScript'
      Inline: |
        Get-NetstorageUploadAccount -UploadAccountID 'akamaipowershell'
      azurePowerShellVersion: 'LatestVersion'
      pwsh: true
