
trigger: none

pool:
  vmImage: 'windows-2025'

variables:
  - group: akamai

steps:
  - task: PowerShell@2
    displayName: 'Run Maintenance Script with PowerShell'
    inputs:
      targetType: 'inline'
      script: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module Akamai.Netstorage -Force -Scope CurrentUser
        Get-NetstorageUploadAccount -UploadAccountID akamaipowershell
      pwsh: true
