
trigger: none

parameters:
  - name: Environment
    type: string
    default: Production
    values:
      - Production
      - Staging
      - RC
      - PPE

pool:
  vmImage: 'windows-latest'

variables:
  group: akamai-creds

steps:
  - task: AzurePowerShell@5
    displayName: 'Run Maintenance Script with Azure PowerShell'
    env:
      AKAMAI_HOST: $(AkamaiHost)
      AKAMAI_CLIENT_TOKEN: $(AkamaiClientToken)
      AKAMAI_ACCESS_TOKEN: $(AkamaiAccessToken)
      AKAMAI_CLIENT_SECRET: $(AkamaiClientSecret)
    inputs:
      # link to set up a service connection: https://aka.ms/azure-pipelines-service-connection
      azureSubscription: 'serv-con'
      ScriptType: 'InlineScript'
      Inline: |
        Install-Module Akamai.Netstorage
        Get-NetstorageUploadAccount -UploadAccountID 'akamaipowershell'
      azurePowerShellVersion: 'LatestVersion'
      pwsh: true
