name: publish-edgeworker-pwsh
on: 
  push:
    branches:
      - main
    paths:
      - 'edgeworkers/**'
  workflow_dispatch:

env:
  AKAMAI_HOST: ${{ secrets.akamai_host }}
  AKAMAI_CLIENT_TOKEN: ${{ secrets.akamai_client_token }}
  AKAMAI_ACCESS_TOKEN: ${{ secrets.akamai_access_token }}
  AKAMAI_CLIENT_SECRET: ${{ secrets.akamai_client_secret }}
  ACCOUNT_KEY: ${{ vars.ACCOUNT_KEY }}

jobs:
  Deploy-EdgeWorker:
    runs-on: ubuntu-latest
    container: stuartmacleod/akamaipowershell:latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - run: |
            New-EdgeWorkerVersion -EdgeWorkerName ${{ vars.EW_NAME }} -CodeDirectory edgeworkers
            $Version = (Get-Content edgeworkers/bundle.json -Raw | ConvertFrom-Json).'edgeworker-version'
            Deploy-EdgeWorker -EdgeWorkerName ${{ vars.EW_NAME }} -Version $Version -Network STAGING