name: publish-edgeworker
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: stuartmacleod/akamaipowershell:latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v3
      - run: Set-Content -Path ~/.edgerc -Value "[default]`nhost=${{ secrets.akamai_host }}`nclient_token=${{ secrets.akamai_client_token }}`naccess_token=${{ secrets.akamai_access_token }}`nclient_secret=${{ secrets.akamai_client_secret }}"
      - run: |
            Import-Module AkamaiPowerShell -DisableNameChecking
            New-EdgeWorkerVersion -Name ${{ vars.EW_NAME }} -CodeDirectory .
