name: publish-edgeworker
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: akamai/edgeworkers:latest
    env:
      AKAMAI_DEFAULT_HOST: ${{ secrets.akamai_host }}
      AKAMAI_DEFAULT_CLIENT_TOKEN: ${{ secrets.akamai_client_token }}
      AKAMAI_DEFAULT_ACCESS_TOKEN: ${{ secrets.akamai_access_token }}
      AKAMAI_DEFAULT_CLIENT_SECRET: ${{ secrets.akamai_client_secret }}
    steps:
      - uses: actions/checkout@v3
      - run: akamai edgeworkers --accountkey ${{ vars.ACCOUNT_KEY }} upload --codeDir . ${{ vars.EW_ID }}
