name: publish-edgeworker
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: akamai/edgeworkers:latest
    env:
      AKAMAI_DEFAULT_HOST: ${{ secrets.akamai_host }}
      AKAMAI_DEFAULT_CLIENT_TOKEN: ${{ secrets.akamai_client_token }}
      AKAMAI_DEFAULT_ACCESS_TOKEN: ${{ secrets.akamai_access_token }}
      AKAMAI_DEFAULT_CLIENT_SECRET: ${{ secrets.akamai_client_secret }}
    steps:
      - uses: actions/checkout@v3
      - run: echo -e "[default]\nhost=${{ secrets.akamai_host }}\nclient_token=${{ secrets.akamai_client_token }}\naccess_token=${{ secrets.akamai_access_token }}\nclient_secret=${{ secrets.akamai_client_secret }}" > ~/.edgerc
      - run: akamai edgeworkers upload --codeDir . ${{ vars.EW_ID }}
      - run: VERSION=$(cat bundle.json | grep edgeworker-version | sed -E 's/.*edgeworker-version\": \"([^"]+).*/\1/')
      - run akamai edgeworkers activate ${{ vars.EW_ID }} staging $VERSION
