name: publish-edgeworker
on: 
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: akamai/edgeworkers:latest
    steps:
      - uses: actions/checkout@v3
      - run: echo -e "[default]\nhost=${{ secrets.akamai_host }}\nclient_token=${{ secrets.akamai_client_token }}\naccess_token=${{ secrets.akamai_access_token }}\nclient_secret=${{ secrets.akamai_client_secret }}" > ~/.edgerc
      - run: akamai edgeworkers upload --codeDir . ${{ vars.EW_ID }}
  push-to-staging:
    needs: deploy
    runs-on: ubuntu-latest
    container: akamai/edgeworkers:latest
    steps:
      - uses: actions/checkout@v3
      - run: echo -e "[default]\nhost=${{ secrets.akamai_host }}\nclient_token=${{ secrets.akamai_client_token }}\naccess_token=${{ secrets.akamai_access_token }}\nclient_secret=${{ secrets.akamai_client_secret }}" > ~/.edgerc
      - run: |
              VERSION=$(cat bundle.json | grep edgeworker-version | sed -E "s/.*edgeworker-version\": \"([^\"]+).*/\1/")
              akamai edgeworkers activate ${{ vars.EW_ID }} staging $VERSION
  push-to-production:
    needs: push-to-staging
    environment: production
    runs-on: ubuntu-latest
    container: akamai/edgeworkers:latest
    steps:
      - uses: actions/checkout@v3
      - run: echo -e "[default]\nhost=${{ secrets.akamai_host }}\nclient_token=${{ secrets.akamai_client_token }}\naccess_token=${{ secrets.akamai_access_token }}\nclient_secret=${{ secrets.akamai_client_secret }}" > ~/.edgerc
      - run: |
              VERSION=$(cat bundle.json | grep edgeworker-version | sed -E "s/.*edgeworker-version\": \"([^\"]+).*/\1/")
              akamai edgeworkers activate ${{ vars.EW_ID }} production $VERSION

