name: publish-property
on: 
  push:
    branches:
      - main
    paths:
      - 'property/**'
  workflow_dispatch:

env:
  AKAMAI_HOST: ${{ secrets.akamai_host }}
  AKAMAI_CLIENT_TOKEN: ${{ secrets.akamai_client_token }}
  AKAMAI_ACCESS_TOKEN: ${{ secrets.akamai_access_token }}
  AKAMAI_CLIENT_SECRET: ${{ secrets.akamai_client_secret }}
  # AKAMAI_ACCOUNT_KEY: ${{ vars.ACCOUNT_KEY }}

jobs:
  Update-Property:
    runs-on: ubuntu-latest
    container: stuartmacleod/akamaipowershell:latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
      - run: |
            $Notes = "Github Action:`n  Branch: ${{ github.ref_name }}`n  Author: ${{ github.event.pusher.name }}`n  Message: ${{ github.event.head_commit.message }}`n  Sha: ${{ github.sha }}"
            New-PropertyVersion -PropertyName ${{ vars.PROPERTY_NAME }} -CreateFromVersion latest
            Set-PropertyRules -PropertyName ${{ vars.PROPERTY_NAME }} -PropertyVersion latest -InputDirectory property -VersionNotes $Notes
  Push-To-Staging:
    needs: Update-Property
    runs-on: ubuntu-latest
    container: stuartmacleod/akamaipowershell:latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
      - run: |
            $Activation = Deploy-Property -PropertyName ${{ vars.PROPERTY_NAME }} -PropertyVersion latest -Network Staging -NotifyEmails ${{ vars.CONTACT_EMAIL }}
            $Status = Get-PropertyActivation -PropertyName ${{ vars.PROPERTY_NAME }} -ActivationID $Activation.activationID
            while($Status.status -eq 'PENDING'){
                Start-Sleep -s 30
                $Status = Get-PropertyActivation -PropertyName ${{ vars.PROPERTY_NAME }} -ActivationID $Activation.activationID
            }
