name: test-python
on: 
  push:
    branches:
      - main
    paths:
      - '**.py'
  workflow_dispatch:

env:
  AKAMAI_HOST: ${{ secrets.akamai_host }}
  AKAMAI_CLIENT_TOKEN: ${{ secrets.akamai_client_token }}
  AKAMAI_ACCESS_TOKEN: ${{ secrets.akamai_access_token }}
  AKAMAI_CLIENT_SECRET: ${{ secrets.akamai_client_secret }}
  ACCOUNT_KEY: ${{ vars.ACCOUNT_KEY }}

jobs:
  execute:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: ["3.12"]
  
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run script.py
      run: python script.py --akamai_host ${{ secrets.akamai_host }} --akamai_client_token ${{ secrets.akamai_client_token }} --akamai_access_token ${{ secrets.akamai_access_token }} --akamai_client_secret ${{ secrets.akamai_client_secret }}